version: "3"
services:
    wordpress:
        image: wordpress
        ports:
            - "8081:80"
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: "secretpass"
            WORDPRESS_DB_NAME: wordpress
        depends_on:
            - mysql
    mysql:
        platform: linux/x86_64
        image: "mysql:5.7"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: "secretpass"
            
